In [7]:
import pandas as pd

data = pd.read_csv('recipe_recommendations.csv')

data

,product,product_english,recipe_name,cooking_time,servings,instructions,recipe_url,missing_ingredients
0,Zelenka Krůtí mletý polotovar,ground turkey,Blue Cheese and Mushroom Turkey Burger,45,1,<ol><li>Mix all your ingredients together and ...,https://www.foodista.com/recipe/3JGSVVX8/blue-...,"['garlic cloves', 'onion', 'portabello mushroo..."
1,Zelenka Krůtí mletý polotovar,ground turkey,Turkey-Spinach Burgers With Sweet Soy-Ginger S...,45,4,"<ol><li>In small saucepan, combine soy sauce, ...",https://www.foodista.com/recipe/CC4PQZMN/turke...,"['baby spinach', 'ginger', 'mirin', 'scallions..."
2,Česká krůta Krůtí mletý polotovar,turkey,Easy Weekday Breakfast Muffins,30,12,InstructionsHeat oven to 350. Whisk eggs toget...,https://www.pinkwhen.com/easy-weekday-breakfas...,"['bell pepper', 'eggs', 'milk', 'sm onion', 'p..."
3,Česká krůta Krůtí mletý polotovar,turkey,Monte Carlo Sandwich,45,9,<ol><li>Spread butter on each slice of bread. ...,https://www.foodista.com/recipe/QSKMGBYY/monte...,"['butter', 'cheese', 'ham', 'eggs', 'milk', 's..."
4,MSC Čerstvé mušle Super,mussels,Mussels Fra Diavolo,45,4,<ol><li>Place a large sauce pot over medium he...,https://www.foodista.com/recipe/6K83VL32/musse...,"['leafs basil', 'wine', ""mamma lombardi's arra..."
5,MSC Čerstvé mušle Super,mussels,Mussels Marinated In Oil and Herbs,45,4,<ol><li>Steam fresh mussels open as directed i...,https://www.foodista.com/recipe/HJY2NCN3/musse...,"['green onions', 'a mixture of herbs', 'vermou..."
6,Sutcha Vepřová krkovice v marinádě pomeranč a ...,pork,The Scotch Egg,45,6,Hard boil your eggs. To get perfectly hard bo...,https://www.foodista.com/recipe/VS7W2DW5/the-s...,"['eggs', 'panko breadcrumbs']"
7,Sutcha Vepřová krkovice v marinádě pomeranč a ...,pork,Kalua Pig,45,1,<ol><li>Make deep slashes in pork. Rub rock sa...,http://www.foodista.com/recipe/T5HZW7DZ/kalua-pig,"['banana leaves', 'bot liquid smoke']"

In [8]:
import pandas as pd

data = pd.read_csv('recipe_recommendations2.csv')

data

,product,product_english,recipe_name,cooking_time,servings,instructions,recipe_url,missing_ingredients
0,Zelenka Krůtí mletý polotovar,ground turkey,Blue Cheese and Mushroom Turkey Burger,45,1,<ol><li>Mix all your ingredients together and ...,https://www.foodista.com/recipe/3JGSVVX8/blue-...,"['garlic cloves', 'onion', 'portabello mushroo..."
1,Zelenka Krůtí mletý polotovar,ground turkey,Chavrie Stuffed Turkey Burgers,45,6,<ol><li>Slice Chavrie goat cheese log into 6 e...,https://www.foodista.com/recipe/5ZHK4WKR/chavr...,"['ea. eggs', '½ garlic', 'chavrie goat cheese'..."
2,Česká krůta Krůtí mletý polotovar,turkey,Easy Weekday Breakfast Muffins,30,12,InstructionsHeat oven to 350. Whisk eggs toget...,https://www.pinkwhen.com/easy-weekday-breakfas...,"['bell pepper', 'eggs', 'milk', 'sm onion', 'p..."
3,Česká krůta Krůtí mletý polotovar,turkey,Monte Carlo Sandwich,45,9,<ol><li>Spread butter on each slice of bread. ...,https://www.foodista.com/recipe/QSKMGBYY/monte...,"['butter', 'butter and oil', 'cheese', 'ham', ..."
4,MSC Čerstvé mušle Super,mussels,Mussels Fra Diavolo,45,4,<ol><li>Place a large sauce pot over medium he...,https://www.foodista.com/recipe/6K83VL32/musse...,"['leafs basil', 'wine', ""mamma lombardi's arra..."
5,MSC Čerstvé mušle Super,mussels,Neoguri (Spicy Seafood Ramen),45,1,<ol><li>1. Add mussels and sauce packets into ...,https://www.foodista.com/recipe/77PG3GGF/neogu...,"['egg', 'neoguri ramen', 'scallion', 'seaweed']"
6,Sutcha Vepřová krkovice v marinádě pomeranč a ...,pork,All Day Simple Slow-Cooker FALL OFF the BONE Ribs,45,4,Portion 2 slabs to allow them to fit in the sl...,https://www.foodista.com/recipe/WKSRCLNF/all-d...,"['broth', ""bbq sauce *i didn't need that much ..."

In [10]:
import pandas as pd

recip = pd.read_csv('recipes.csv')

recip[['product', 'product_english', 'recipe_name']]

,product,product_english,recipe_name
0,Gurmet Hovězí tatarák,beef,Bacon Wrapped Filet Mignon
1,Gurmet Hovězí tatarák,beef,Hot Sliced Beef
2,Toro Hlavečník Hovězí uzené Bavet,beef,Bacon Wrapped Filet Mignon
3,Toro Hlavečník Hovězí uzené Bavet,beef,Hot Sliced Beef
4,"Nature's Meadow Jehněčí kolínko zadní, 1 ks",lamb,Lamb and Fresh Goat Cheese Roulade
5,"Nature's Meadow Jehněčí kolínko zadní, 1 ks",lamb,Easy Garlic Roast Leg Of Lamb With Rosemary an...
6,Medusa Smažené filety ze sardelí,anchovies,Skye Gyngell's Anchovy and Walnut Sauce
7,Vette & Verhaart Srdcovky čerstvé,beef,Bacon Wrapped Filet Mignon
8,Vette & Verhaart Srdcovky čerstvé,beef,Hot Sliced Beef
9,Ecoproduct BIO Hovězí krk,beef,Bacon Wrapped Filet Mignon
10,Ecoproduct BIO Hovězí krk,beef,Hot Sliced Beef
11,FJORU ASC Krevety vařené loupané na špejli 36/40,shrimp,Beer - Batter Fried Shrimp
12,"MASO! Hovězí Burger s lojem, 2 ks",beef,Bacon Wrapped Filet Mignon
13,"MASO! Hovězí Burger s lojem, 2 ks",beef,Hot Sliced Beef
14,Les Landes Francouzské kuře Label Rouge,chicken,Zucchini Chicken Omelette
15,Les Landes Francouzské kuře Label Rouge,chicken,Lemon and Garlic Slow Roasted Chicken
16,Sutcha Brisket hovězí hrudí ze Severní Ameriky,beef,Bacon Wrapped Filet Mignon
17,Sutcha Brisket hovězí hrudí ze Severní Ameriky,beef,Hot Sliced Beef

In [9]:
import pandas as pd

products = pd.read_csv('./rohlikData/products6.csv')


products

,id,date,datetime,name,current_price,original_price,discount,weight,price_per_kg,expiry_date,is_available
0,31,2025-02-05,2025-02-05 14:47:12,Gurmet Hovězí tatarák,54.94,99.90,45,0.250,219.76,2025-02-06,t
1,32,2025-02-05,2025-02-05 14:47:12,MASO! Vepřové kostky na guláš,164.40,194.00,15,0.800,206.66,2025-02-07,t
2,33,2025-02-05,2025-02-05 14:47:12,Toro Hlavečník Hovězí uzené Bavet,224.60,265.00,15,0.410,544.35,2025-02-11,t
3,34,2025-02-05,2025-02-05 14:47:12,"Nature's Meadow Jehněčí kolínko zadní, 1 ks",232.01,356.95,35,0.510,454.92,2025-02-06,t
4,35,2025-02-05,2025-02-05 14:47:12,Medusa Smažené filety ze sardelí,71.44,129.90,45,0.120,595.33,2025-02-09,t
5,36,2025-02-05,2025-02-05 14:47:12,Vette & Verhaart Srdcovky čerstvé,69.96,199.90,65,0.500,139.92,2025-02-06,t
6,37,2025-02-05,2025-02-05 14:47:12,Ecoproduct BIO Hovězí krk,186.69,266.70,30,0.580,321.93,2025-02-10,t
7,38,2025-02-05,2025-02-05 14:47:12,FJORU ASC Krevety vařené loupané na špejli 36/40,149.43,229.90,35,0.195,766.31,2025-02-06,t
8,39,2025-02-05,2025-02-05 14:47:12,"MASO! Hovězí Burger s lojem, 2 ks",88.56,123.00,28,0.400,223.19,2025-02-06,t
9,40,2025-02-05,2025-02-05 14:47:12,Pangas dolnooký filet (rozmrazeno),56.70,80.97,29,0.270,210.00,2025-02-06,t
10,41,2025-02-05,2025-02-05 14:47:12,Les Landes Francouzské kuře Label Rouge,313.99,592.45,47,1.480,211.94,2025-02-07,t
11,42,2025-02-05,2025-02-05 14:47:12,Sutcha Brisket hovězí hrudí ze Severní Ameriky,747.45,1359.00,45,2.720,275.06,2025-02-07,t